// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_loglik_a
double calc_loglik_a(double a, NumericVector y, NumericVector mu, NumericVector sf);
RcppExport SEXP _SAVER_calc_loglik_a(SEXP aSEXP, SEXP ySEXP, SEXP muSEXP, SEXP sfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sf(sfSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_loglik_a(a, y, mu, sf));
    return rcpp_result_gen;
END_RCPP
}
// calc_loglik_b
NumericVector calc_loglik_b(NumericVector b, NumericVector y, NumericVector mu, NumericVector sf);
RcppExport SEXP _SAVER_calc_loglik_b(SEXP bSEXP, SEXP ySEXP, SEXP muSEXP, SEXP sfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sf(sfSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_loglik_b(b, y, mu, sf));
    return rcpp_result_gen;
END_RCPP
}
// calc_loglik_k
NumericVector calc_loglik_k(NumericVector k, NumericVector y, NumericVector mu, NumericVector sf);
RcppExport SEXP _SAVER_calc_loglik_k(SEXP kSEXP, SEXP ySEXP, SEXP muSEXP, SEXP sfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sf(sfSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_loglik_k(k, y, mu, sf));
    return rcpp_result_gen;
END_RCPP
}
// gammaln
NumericVector gammaln(NumericVector x);
RcppExport SEXP _SAVER_gammaln(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaln(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SAVER_calc_loglik_a", (DL_FUNC) &_SAVER_calc_loglik_a, 4},
    {"_SAVER_calc_loglik_b", (DL_FUNC) &_SAVER_calc_loglik_b, 4},
    {"_SAVER_calc_loglik_k", (DL_FUNC) &_SAVER_calc_loglik_k, 4},
    {"_SAVER_gammaln", (DL_FUNC) &_SAVER_gammaln, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SAVER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
