# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_loglik_b <- function(b, y, mu, sf) {
    .Call(`_SAVER_calc_loglik_b`, b, y, mu, sf)
}

gammaln <- function(x) {
    .Call(`_SAVER_gammaln`, x)
}

