# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_abk <- function(y, mu, sf, type, samp) {
    .Call(`_SAVER_calc_abk`, y, mu, sf, type, samp)
}

calc_loglik_a <- function(a, y, mu, sf) {
    .Call(`_SAVER_calc_loglik_a`, a, y, mu, sf)
}

calc_loglik_b <- function(b, y, mu, sf) {
    .Call(`_SAVER_calc_loglik_b`, b, y, mu, sf)
}

calc_loglik_k <- function(k, y, mu, sf) {
    .Call(`_SAVER_calc_loglik_k`, k, y, mu, sf)
}

gammaln <- function(x) {
    .Call(`_SAVER_gammaln`, x)
}

